export const constants = {
  FAILED_TO_FIND_USER: 'failed to find user',
  FAILED_TO_SAVE_USER: 'failed to save user',
  FAILED_TO_UPDATE_USER: 'failed to update user',
  FAILED_TO_DELETE_USER: 'failed to delete user',
  FAILED_TO_CHECK_IF_USER_EXISTS: 'failed to check if user exists',
  FAILED_TO_GET_USER_BY_EMAIL: 'failed to get user by email',
  FAILED_TO_FIND_BY_PHONE_NUMBER: 'failed to find user by phone number',
  FAILED_TO_LIST_USERS: 'failed to list users',
  USER_NOT_FOUND: 'user not found',
  USER_EXISTS: 'user already exists',

  USER_FOUND: 'User found',
  USER_LISTED: 'users listed',
  USER_CREATED: 'User created',
  USER_UPDATED: 'User updated',
  USER_DELETED: 'User deleted',

  FIRST_NAME_SHOULD_BE_STRING: 'firstName should be a string',
  MIDDLE_NAME_SHOULD_BE_STRING: 'middleName should be a string',
  COUNTRY_CODE_SHOULD_BE_A_STRING: 'country code should be a string',
  PHONE_NUMBER_SHOULD_BE_A_STRING: 'phoneNumber should be a string',
  LAST_NAME_SHOULD_BE_STRING: 'lastName should be a string',
  EMAIL_SHOULD_BE_VALID: 'email should be valid',
  EMAIL_OR_PHONENUMBER_IS_REQURIED: 'email or phoneNumber is required',
  PASSWORD_SHOULD_BE_VALID_STRING: 'password should be a valid string',
  ENABLED_SHOULD_BE_VALID_BOOLEAN: 'enabled should be a valid boolean',
  COUNTRY_CODE_SHOULD_BE_REQURIED: 'country code should be requried',
  PASSWORD_IS_REQUIRED: 'password is required',
  USER_SEARCH_SHOULD_BE_STRING: 'user search should be string',
} as const;
